<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="garp_amr">
    <!--
        GARP AMR - Gazebo Pluginleri
        GARP uyumlu
    -->

    <gazebo>
        <!-- JOINT STATE PUBLISHER -->
        <plugin
            filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>garp/joint_states</topic>
            <joint_name>base_TO_wh_l</joint_name>
            <joint_name>base_TO_wh_r</joint_name>
        </plugin>

        <!-- DİFERANSİYEL SÜRÜŞ -->
        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <topic>garp/cmd_vel</topic>
            <left_joint>base_TO_wh_l</left_joint>
            <right_joint>base_TO_wh_r</right_joint>
            <wheel_separation>${(chasis_len_y / 2.0 + wh_thick / 2.0 + wh_chasis_gap) * 2}</wheel_separation>
            <wheel_radius>${wh_radius}</wheel_radius>
            <max_linear_acceleration>1.0</max_linear_acceleration>
            <max_angular_acceleration>2.0</max_angular_acceleration>
            <max_linear_velocity>1.0</max_linear_velocity>
            <max_angular_velocity>2.0</max_angular_velocity>
            <odom_frame>odom_frame</odom_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>

        <!-- ODOMETRİ PUBLISHER -->
        <plugin
            filename="gz-sim-odometry-publisher-system"
            name="gz::sim::systems::OdometryPublisher">
            <odom_topic>garp/odom</odom_topic>
            <odom_frame>odom_frame</odom_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
            <odom_publish_frequency>50</odom_publish_frequency>
            <dimensions>3</dimensions>
        </plugin>

    </gazebo>

</robot>
