<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="garp_amr">
    <!--
        GARP AMR - Sensör Tanımları
        LIDAR - GARP uyumlu
    -->

    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.02"/>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="chasis_TO_lidar" type="fixed">
        <parent link="chasis"/>
        <child link="lidar"/>
        <origin xyz="0 0 ${chasis_len_z / 2.0 + lidar_length / 2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar">
        <sensor name="gpu_lidar" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <topic>lidar/scan</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.57</min_angle>
                        <max_angle>1.57</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>15.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <gz_frame_id>lidar</gz_frame_id>
        </sensor>
    </gazebo>

</robot>
