<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="garp_amr">
    <!--
        GARP AMR - Tekerlek Tanımları
        Tahrik ve Caster Tekerlekleri
        (GARP için düzenlendi)
    -->

    <!-- ==================== TAHRİK TEKER PARAMETRELERİ ==================== -->
    <xacro:property name="wh_radius" value="0.1"/>
    <xacro:property name="wh_thick" value="0.04"/>
    <xacro:property name="wh_chasis_gap" value="0.001"/>
    <xacro:property name="wh_mass" value="1.0"/>

    <!-- ==================== AVARE TEKER PARAMETRELERİ ==================== -->
    <xacro:property name="cwh_chasis_offset_xy" value="0.1"/>
    <!-- Yarıçap dinamik hesaplanıyor: zemine tam değecek şekilde -->
    <xacro:property name="cwh_radius" value="${(wh_radius - (chasis_len_z / 2.0 - base_chasis_offset)) / 2.0}"/>
    <xacro:property name="cwh_mass" value="0.00001"/>

    <!-- ==================== TAHRİK TEKERLEĞİ MAKROSU ==================== -->
    <xacro:macro name="create_wh" params="postfix yfact">

        <joint name="base_TO_wh_${postfix}" type="continuous">
            <origin xyz="0.0 ${yfact * (chasis_len_y / 2.0 + wh_thick / 2.0 + wh_chasis_gap)} 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="wh_${postfix}"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>

        <link name="wh_${postfix}">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <mass value="${wh_mass}"/>
                <inertia 
                    ixx="${wh_mass * (3*wh_radius*wh_radius + wh_thick*wh_thick) / 12.0}"
                    iyy="${wh_mass * (3*wh_radius*wh_radius + wh_thick*wh_thick) / 12.0}"
                    izz="${wh_mass * (wh_radius*wh_radius) / 2.0}"
                    ixy="0" ixz="0" iyz="0"/>
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wh_radius}" length="${wh_thick}"/>
                </geometry>
                <material name="gray"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wh_radius}" length="${wh_thick}"/>
                </geometry>
            </collision>
        </link>

        <!-- Tahrik tekerleği için yüksek sürtünme -->
        <gazebo reference="wh_${postfix}">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
        </gazebo>

    </xacro:macro>

    <!-- ==================== AVARE TEKER MAKROSU ==================== -->
    <xacro:macro name="create_cwh" params="postfix xfact yfact">

        <joint name="chasis_TO_cwh_${postfix}" type="fixed">
            <origin xyz="${xfact * (chasis_len_x / 2.0 - cwh_chasis_offset_xy)} 
                        ${yfact * (chasis_len_y / 2.0 - cwh_chasis_offset_xy)} 
                        ${-1 * (chasis_len_z / 2.0 + cwh_radius)}" rpy="0 0 0"/>
            <parent link="chasis"/>
            <child link="cwh_${postfix}"/>
        </joint>

        <link name="cwh_${postfix}">
            <inertial>
                <mass value="0.01"/>
                <origin xyz="0 0 0"/>
                <inertia
                    ixx="1e-5" ixy="0" ixz="0"
                    iyy="1e-5" iyz="0"
                    izz="1e-5"/>
            </inertial>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${cwh_radius}"/>
                </geometry>
                <material name="gray"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${cwh_radius}"/>
                </geometry>
            </collision>
        </link>

        <!-- Caster için çok düşük sürtünme (kaymalı) -->
        <gazebo reference="cwh_${postfix}">
            <collision>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.001</mu>
                            <mu2>0.001</mu2>
                            <slip1>1.0</slip1>
                            <slip2>1.0</slip2>
                        </ode>
                    </friction>
                    <bounce>
                        <restitution_coefficient>0.0</restitution_coefficient>
                    </bounce>
                </surface>
            </collision>
        </gazebo>

    </xacro:macro>

</robot>
